spring:
    datasource:
        dataSourceClassName: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
        url: jdbc:mysql://localhost:3306/balero_v2
        databaseName:
        serverName:
        username: root
        password:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
    jpa:
      show_sql: false
      hibernate:
        ddl-auto: update
    thymeleaf:
      cache: false
    logging:
      level:
          org:
            springframework:
              web: DEBUG
          hibernate: ERROR

# FLYWAY (FlywayProperties)
flyway:
  validateOnMigrate: false