spring:
    mail:
        protocol: smtp
        host: smtp.gmail.com
        port: 587
        username: yourusername@gmail.com
        password: yourpassword
        smtp:
            auth: true
            starttls: true